# Test the "GET /api/joke" Route
GET http://localhost:3000/api/joke
###

# Test the "GET /api/joke/:id" Route
GET http://localhost:3000/api/joke/67b38a49aa78fdd528177f45
###

# Test the "POST /api/joke/:id" Route - Voting on a joke
# Sending the like again if you have already liked it will remove the like
# If you have like a joke and try to cast `love` vote the like vote will be removed and the love vote will be casted.
POST http://localhost:3000/api/joke/67b38a49aa78fdd528177f45 HTTP/1.1
content-type: application/json

{
  "value": "love"
}

###

# Test invalid vote action
POST http://localhost:3000/api/joke/67b38a49aa78fdd528177f45 HTTP/1.1
content-type: application/json

{
  "value": "upvote"
}

###

# Test the "PUT /api/joke/:id" Route - Updating joke content
PUT http://localhost:3000/api/joke/67b38a49aa78fdd528177f45 HTTP/1.1
content-type: application/json

{
  "question": "Why did the chicken join a band?",
  "answer": "Because it had the drumsticks!"
}
###

# Test updating only the question
PUT http://localhost:3000/api/joke/67b38a49aa78fdd528177f45 HTTP/1.1
content-type: application/json

{
  "question": "Why don't skeletons fight each other?"
}
###

# Test updating only the answer
PUT http://localhost:3000/api/joke/67b38a49aa78fdd528177f45 HTTP/1.1
content-type: application/json

{
  "answer": "Because they don't have the guts!"
}
###

# Test invalid update (no question or answer provided)
PUT http://localhost:3000/api/joke/67b38a49aa78fdd528177f45 HTTP/1.1
content-type: application/json

{
  "answer": "a",
  "question": ""
}
###

# Test to delete a vote
DELETE  http://localhost:3000/api/joke/67b38a49aa78fdd528177f45 HTTP/1.1

###